### ISSUE TITLE
stuck with installation of mapeditor at step 5.

### ISSUE THREAD

**Issue by stanklerks** [ESDLMapEditorESSIM/docker-toolsuite#24]
Hey,

i'm trying to get a local installation on a windows 11 machine  of ESDL running and can't get it to work. When i follow the procedure from https://github.com/ESDLMapEditorESSIM/docker-toolsuite?tab=readme-ov-file it works untill step 5. After that i get the following warning. 

_level=warning msg="a network with name mapeditor-net exists but was not created for project \"essim\".\nSet external: true to use an existing network"_

I can continue to load esdlmapeditor and esdldrive but they give a similar error. In the end http://localhost:8111 does not respond.

If someone could point me in the right direction, that would be great. I run docker engine v27.5.1. 

Stan.

**Comment by ewoudwerkman** [comment]
Hi Stan,

What could be the case is that newer docker versions have a more strict check on the definition of external networks (in this case `mapeditor_net`. As a quick fix, could you change in the `docker-compose.yml` files in the folders of `ESSIM`, `ESDLMapeditor` and `ESDLDrive`

```yaml
networks:
  mapeditor-net:
    name: mapeditor-net
```

into 
```yaml
networks:
  mapeditor-net:
    name: mapeditor-net
    external: true
```

make sure there are 4 spaces before `external: true`
`docker compose up` in each of these folders should now hopefully work.
